### ISSUE TITLE
Cannot read property 'EXTENSION_SEARCHSYNC_CONFIG_PATH' of undefined

### ISSUE THREAD

**Issue by usamecavga** [dimitrov-adrian/directus-extension-searchsync#12]
Hi,

I get error below after update directus to 9.1.2

⚠️  Couldn't register hook "directus-extension-searchsync"
⚠️  Cannot read property 'EXTENSION_SEARCHSYNC_CONFIG_PATH' of undefined

**Comment by dimitrov-adrian** [comment]
It should be fixed with latest version. @usamecavga could you validate please.

**Comment by sarente** [comment]
Hi,

There are some errors belongs to node version;

Now using node v16.10.0 (npm v7.24.0) and Now using node v14.16.0 (npm v6.14.11)

⚠️  Couldn't register hook "directus-extension-searchsync"
⚠️  Cannot find module 'cosmiconfig'

-----------------------------------------------------------------------------------

Now using node v12.20.2 (npm v7.24.1)

⚠️  Couldn't register hook "directus-extension-searchsync"
⚠️  Unexpected token '.'

**Comment by usamecavga** [comment]
Hi,

There are some errors belongs to node version;

Now using node v16.10.0 (npm v7.24.0) and Now using node v14.16.0 (npm v6.14.11)

⚠️ Couldn't register hook "directus-extension-searchsync"
⚠️ Cannot find module 'cosmiconfig'

Now using node v12.20.2 (npm v7.24.1)

⚠️ Couldn't register hook "directus-extension-searchsync"
⚠️ Unexpected token '.'

**Comment by dimitrov-adrian** [comment]
Oh, yes in Node 12 there was issue indeed, it should be fixed with latest 1.0.2. I have tested it with Node 12, 14 and 16

About the first error, ensure you install it with `npm install dimitrov-adrian/directus-extension-searchsync`

**Comment by usamecavga** [comment]
Hi,

There are some errors too.

Now using node v12.20.2 (npm v7.24.1) and Now using node v14.16.0 (npm v6.14.11) and Now using node v16.10.0 (npm v7.24.0) 

14:33:12 ⚠️  Couldn't register hook "directus-extension-searchsync"
14:33:12 ⚠️  Cannot find module 'axios'

**Comment by dimitrov-adrian** [comment]
How you install it? axios should be installed already by directus, and the extension is defining it as peer dependency.

**Comment by usamecavga** [comment]
Hi,

```
yarn add dimitrov-adrian/directus-extension-searchsync
yarn add v1.22.10

[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > directus-extension-searchsync@1.0.2" has unmet peer dependency "axios@^0.24.0".
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
warning No license field
success Saved 25 new dependencies.
info Direct dependencies
└─ directus-extension-searchsync@1.0.2
info All dependencies
├─ @babel/code-frame@7.16.0
├─ @babel/helper-validator-identifier@7.15.7
├─ @babel/highlight@7.16.0
├─ @types/parse-json@4.0.0
├─ ansi-styles@3.2.1
├─ callsites@3.1.0
├─ chalk@2.4.2
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ cosmiconfig@7.0.1
├─ directus-extension-searchsync@1.0.2
├─ error-ex@1.3.2
├─ escape-string-regexp@1.0.5
├─ has-flag@3.0.0
├─ import-fresh@3.3.0
├─ is-arrayish@0.2.1
├─ js-tokens@4.0.0
├─ json-parse-even-better-errors@2.3.1
├─ lines-and-columns@1.2.4
├─ parent-module@1.0.1
├─ parse-json@5.2.0
├─ path-type@4.0.0
├─ resolve-from@4.0.0
├─ supports-color@5.5.0
└─ yaml@1.10.2
✨  Done in 5.16s.
```

**Comment by dimitrov-adrian** [comment]
I do believe you are out of (may be parent) of your directus project directory, and it should be inside.

One more thin (I just saw I made an mistake in the readme) the config files should be one of next

- package.json `"searchsync":{...}`
- .searchsyncrc
- .searchsyncrc.json
- .searchsyncrc.yaml
- .searchsyncrc.yml
- .searchsyncrc.js
- .searchsyncrc.cjs
- searchsync.config.js
- searchsync.config.cjs

**Comment by usamecavga** [comment]
Hi,

I'm in directus directory. And .searchsyncrc.json is near package.json.

When I add axios package with "yarn add axios" it works.

```
{
  "license": "MIT",
  "dependencies": {
    "axios": "^0.24.0",
    "directus-extension-searchsync": "dimitrov-adrian/directus-extension-searchsync",
    "pg": "^8.7.1"
  }
}
```

**Comment by dimitrov-adrian** [comment]
Not sure why this actually happen, but might be better then to include the axios in the actual dependencies.

Thanks for all the feedback!
